-- Códigos CIE-10 del proyecto de historia clínica de la Dra. Gladys que faltaban en la tabla.
-- Solo agrega los que no existen; no modifica ni borra códigos ya cargados.
-- Las descripciones vienen del archivo original; las que terminan en «…» llegaron recortadas.
INSERT INTO "cie_codes" ("id", "code", "description", "version") VALUES
  (gen_random_uuid(), 'A09.0', 'OTRAS GASTROENTERITIS Y COLITIS DE O…', 'CIE-10'),
  (gen_random_uuid(), 'A09.9', 'GASTROENTERITIS Y COLITIS DE ORIGEN…', 'CIE-10'),
  (gen_random_uuid(), 'G73.0', 'SINDROMES MIASTENICOS EN ENFERMED…', 'CIE-10'),
  (gen_random_uuid(), 'G73.1', 'SINDROME DE EATON-LAMBERT (C80†)', 'CIE-10'),
  (gen_random_uuid(), 'G73.2', 'OTROS SINDROMES MIASTENICOS EN EN…', 'CIE-10'),
  (gen_random_uuid(), 'G73.3', 'SINDROMES MIASTENICOS EN OTRAS EN…', 'CIE-10'),
  (gen_random_uuid(), 'G73.4', 'MIOPATIA EN ENFERMEDADES INFECCIOS…', 'CIE-10'),
  (gen_random_uuid(), 'G73.5', 'MIOPATIA EN ENFERMEDADES ENDOCRIN…', 'CIE-10'),
  (gen_random_uuid(), 'G73.6', 'MIOPATIA EN ENFERMEDADES METABOLI…', 'CIE-10'),
  (gen_random_uuid(), 'G73.7', 'MIOPATIA EN OTRAS ENFERMEDADES CL…', 'CIE-10'),
  (gen_random_uuid(), 'K35.2', 'APENDICITIS AGUDA CON PERITONITIS G…', 'CIE-10'),
  (gen_random_uuid(), 'K35.3', 'APENDICITIS AGUDA CON PERITONITIS L…', 'CIE-10'),
  (gen_random_uuid(), 'K35.8', 'OTRAS APENDICITIS AGUDAS, Y LAS NO E…', 'CIE-10'),
  (gen_random_uuid(), 'L89.0', 'ÚLCERA DE DECÚBITO Y POR ÁREA DE PR…', 'CIE-10'),
  (gen_random_uuid(), 'L89.1', 'ÚLCERA DE DECÚBITO - ETAPA II', 'CIE-10'),
  (gen_random_uuid(), 'L89.2', 'ÚLCERA DE DECÚBITO - ETAPA III', 'CIE-10'),
  (gen_random_uuid(), 'L89.3', 'ÚLCERA DE DECÚBITO - ETAPA IV', 'CIE-10'),
  (gen_random_uuid(), 'L89.9', 'ÚLCERA DE DECÚBITO Y POR ÁREA DE PR…', 'CIE-10'),
  (gen_random_uuid(), 'N18.1', 'ENFERMEDAD RENAL CRÓNICA - ETAPA 1', 'CIE-10'),
  (gen_random_uuid(), 'N18.2', 'ENFERMEDAD RENAL CRÓNICA - ETAPA 2', 'CIE-10'),
  (gen_random_uuid(), 'N18.3', 'ENFERMEDAD RENAL CRÓNICA - ETAPA 3', 'CIE-10'),
  (gen_random_uuid(), 'N18.4', 'ENFERMEDAD RENAL CRÓNICA - ETAPA 4', 'CIE-10'),
  (gen_random_uuid(), 'N18.5', 'ENFERMEDAD RENAL CRÓNICA - ETAPA 5', 'CIE-10'),
  (gen_random_uuid(), 'Q31.4', 'ESTRIDOR LARINGEO CONGENITO', 'CIE-10'),
  (gen_random_uuid(), 'Q35.4', 'FISTULA DEL PALADAR DURO Y DEL PALA…', 'CIE-10'),
  (gen_random_uuid(), 'Q35.6', 'FISURA DEL PALADAR, LINEA MEDIA', 'CIE-10'),
  (gen_random_uuid(), 'U04.9', 'SÍNDROME RESPIRATORIO AGUDO GRAV…', 'CIE-10'),
  (gen_random_uuid(), 'U07.1', 'COVID-19 (virus identificado)', 'CIE-10'),
  (gen_random_uuid(), 'U07.2', 'COVID-19 (virus no identificado)', 'CIE-10'),
  (gen_random_uuid(), 'U80.0', 'AGENTE BACTERIANO RESISTENTE A PENI…', 'CIE-10'),
  (gen_random_uuid(), 'U80.1', 'AGENTE BACTERIANO RESISTENTE A METI…', 'CIE-10'),
  (gen_random_uuid(), 'U80.8', 'AGENTE BACTERIANO RESISTENTE A OTR…', 'CIE-10'),
  (gen_random_uuid(), 'U81.0', 'AGENTE BACTERIANO RESISTENTE A VAN…', 'CIE-10'),
  (gen_random_uuid(), 'U81.8', 'AGENTE BACTERIANO RESISTENTE A OTR…', 'CIE-10'),
  (gen_random_uuid(), 'U89.8', 'AGENTE BACTERIANO RESISTENTE A OTR…', 'CIE-10'),
  (gen_random_uuid(), 'U89.9', 'AGENTE BACTERIANO RESISTENTE A ANTI…', 'CIE-10'),
  (gen_random_uuid(), 'W46.0', 'CONTACTO TRAUMÁTICO CON AGUJA HI…', 'CIE-10'),
  (gen_random_uuid(), 'W46.1', 'CONTACTO TRAUMÁTICO CON AGUJA HI…', 'CIE-10'),
  (gen_random_uuid(), 'W46.2', 'CONTACTO TRAUMÁTICO CON AGUJA HI…', 'CIE-10'),
  (gen_random_uuid(), 'W46.3', 'CONTACTO TRAUMÁTICO CON AGUJA HI…', 'CIE-10'),
  (gen_random_uuid(), 'W46.4', 'CONTACTO TRAUMÁTICO CON AGUJA HI…', 'CIE-10'),
  (gen_random_uuid(), 'W46.5', 'CONTACTO TRAUMÁTICO CON AGUJA HI…', 'CIE-10'),
  (gen_random_uuid(), 'W46.6', 'CONTACTO TRAUMÁTICO CON AGUJA HI…', 'CIE-10'),
  (gen_random_uuid(), 'W46.7', 'CONTACTO TRAUMÁTICO CON AGUJA HI…', 'CIE-10'),
  (gen_random_uuid(), 'W46.8', 'CONTACTO TRAUMÁTICO CON AGUJA HI…', 'CIE-10'),
  (gen_random_uuid(), 'W46.9', 'CONTACTO TRAUMÁTICO CON AGUJA HI…', 'CIE-10')
ON CONFLICT ("code") DO NOTHING;
