export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CLINIC_ADMIN = 'CLINIC_ADMIN',
}

export enum ClinicSpecialty {
  PSYCHOLOGY = 'PSYCHOLOGY',
  DENTISTRY = 'DENTISTRY',
  MEDICINE = 'MEDICINE',
  AESTHETIC = 'AESTHETIC',
}

export enum DashboardType {
  CLINICAL_HISTORY = 'CLINICAL_HISTORY',
  CLINICAL_HISTORY_WITH_DOCS = 'CLINICAL_HISTORY_WITH_DOCS',
}
