export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  HEALTH_PROFESSIONAL = 'HEALTH_PROFESSIONAL',
  RECEPTIONIST = 'RECEPTIONIST',
  AUDITOR = 'AUDITOR',
}

export enum ClinicSpecialty {
  PSYCHOLOGY = 'PSYCHOLOGY',
  DENTISTRY = 'DENTISTRY',
  MEDICINE = 'MEDICINE',
  AESTHETIC = 'AESTHETIC',
  PHYSIOTHERAPY = 'PHYSIOTHERAPY',
  ORTHODONTICS = 'ORTHODONTICS',
}

export enum DashboardType {
  CLINICAL_HISTORY = 'CLINICAL_HISTORY',
  CLINICAL_HISTORY_WITH_DOCS = 'CLINICAL_HISTORY_WITH_DOCS',
}

/** Cita con paciente vs bloqueo de agenda del profesional. */
export enum AppointmentEventType {
  CITA = 'CITA',
  BLOQUEO = 'BLOQUEO',
}
