/**
 * Diagnósticos CIE-10 frecuentes en medicina estética. Solo consultorio AESTHETIC.
 * Códigos y descripciones tomados de la tabla CIE-10 oficial cargada en el sistema;
 * al buscar se completa con el resto del CIE-10.
 */
export const AESTHETIC_CIE_CATALOG: Array<{ code: string; description: string; category: string }> = [
  { code: 'Z41.1', description: 'Otras cirugías plásticas por razones estéticas', category: 'Motivo estético' },
  { code: 'Z41.8', description: 'Otros procedimientos para otros propósitos que no sean los de mejorar el estado de salud', category: 'Motivo estético' },
  { code: 'Z41.9', description: 'Procedimiento no especificado para otros propósitos que no sean los de mejorar el estado de salud', category: 'Motivo estético' },
  { code: 'Z42.8', description: 'Cuidados posteriores a la cirugía plástica de otras partes especificadas del cuerpo', category: 'Motivo estético' },
  { code: 'Z09.8', description: 'Examen de seguimiento consecutivo a otro tratamiento por otras afecciones', category: 'Consulta y control' },
  { code: 'Z00.0', description: 'Examen médico general', category: 'Consulta y control' },
  { code: 'Z71.9', description: 'Consulta, no especificada', category: 'Consulta y control' },

  { code: 'L57.8', description: 'Otros cambios de la piel debidos a exposición crónica a radiación no ionizante', category: 'Envejecimiento y textura' },
  { code: 'L57.9', description: 'Cambios de la piel debidos a exposición crónica a radiación no ionizante, sin otra especificación', category: 'Envejecimiento y textura' },
  { code: 'L57.0', description: 'Queratosis actínica', category: 'Envejecimiento y textura' },
  { code: 'R23.4', description: 'Cambios en la textura de la piel', category: 'Envejecimiento y textura' },
  { code: 'R23.8', description: 'Otros cambios de la piel y los no especificados', category: 'Envejecimiento y textura' },
  { code: 'L90.8', description: 'Otros trastornos atróficos de la piel', category: 'Envejecimiento y textura' },
  { code: 'L90.9', description: 'Trastorno atrófico de la piel, no especificado', category: 'Envejecimiento y textura' },
  { code: 'L85.3', description: 'Xerosis del cutis', category: 'Envejecimiento y textura' },
  { code: 'L98.8', description: 'Otros trastornos especificados de la piel y del tejido subcutáneo', category: 'Envejecimiento y textura' },

  { code: 'L81.1', description: 'Cloasma', category: 'Pigmentación' },
  { code: 'L81.0', description: 'Hiperpigmentación postinflamatoria', category: 'Pigmentación' },
  { code: 'L81.2', description: 'Efélide', category: 'Pigmentación' },
  { code: 'L81.3', description: 'Manchas café con leche', category: 'Pigmentación' },
  { code: 'L81.4', description: 'Otros tipos de hiperpigmentación melanodérmica', category: 'Pigmentación' },
  { code: 'L81.5', description: 'Leucodermia, no clasificada en otra parte', category: 'Pigmentación' },
  { code: 'L81.8', description: 'Otros trastornos especificados de la pigmentación', category: 'Pigmentación' },
  { code: 'L81.9', description: 'Trastorno de la pigmentación, no especificado', category: 'Pigmentación' },
  { code: 'L80X', description: 'Vitíligo', category: 'Pigmentación' },

  { code: 'L70.0', description: 'Acné vulgar', category: 'Acné y rosácea' },
  { code: 'L70.1', description: 'Acné conglobado', category: 'Acné y rosácea' },
  { code: 'L70.8', description: 'Otros acnés', category: 'Acné y rosácea' },
  { code: 'L70.9', description: 'Acné, no especificado', category: 'Acné y rosácea' },
  { code: 'L71.9', description: 'Rosácea, no especificada', category: 'Acné y rosácea' },
  { code: 'L71.0', description: 'Dermatitis peribucal', category: 'Acné y rosácea' },
  { code: 'L73.2', description: 'Hidradenitis supurativa', category: 'Acné y rosácea' },

  { code: 'L90.5', description: 'Fibrosis y afecciones cicatriciales de la piel', category: 'Cicatrices y estrías' },
  { code: 'L91.0', description: 'Cicatriz queloide', category: 'Cicatrices y estrías' },
  { code: 'L90.6', description: 'Estrías atróficas', category: 'Cicatrices y estrías' },

  { code: 'E65X', description: 'Adiposidad localizada', category: 'Contorno corporal' },
  { code: 'E66.9', description: 'Obesidad, no especificada', category: 'Contorno corporal' },
  { code: 'E88.1', description: 'Lipodistrofia, no clasificada en otra parte', category: 'Contorno corporal' },
  { code: 'I83.9', description: 'Venas varicosas de los miembros inferiores sin úlcera ni inflamación', category: 'Vascular' },
  { code: 'I78.1', description: 'Nevo, no neoplásico', category: 'Vascular' },
  { code: 'D18.0', description: 'Hemangioma, de cualquier sitio', category: 'Vascular' },

  { code: 'L64.9', description: 'Alopecia andrógena, no especificada', category: 'Pelo y sudoración' },
  { code: 'L65.9', description: 'Pérdida no cicatricial del pelo, sin otra especificación', category: 'Pelo y sudoración' },
  { code: 'L68.0', description: 'Hirsutismo', category: 'Pelo y sudoración' },
  { code: 'R61.0', description: 'Hiperhidrosis localizada', category: 'Pelo y sudoración' },
  { code: 'R61.9', description: 'Hiperhidrosis, no especificada', category: 'Pelo y sudoración' },

  { code: 'L82X', description: 'Queratosis seborreica', category: 'Lesiones benignas' },
  { code: 'D22.9', description: 'Nevo melanocítico, sitio no especificado', category: 'Lesiones benignas' },
  { code: 'D23.9', description: 'Tumor benigno de la piel, sitio no especificado', category: 'Lesiones benignas' },
  { code: 'L72.0', description: 'Quiste epidérmico', category: 'Lesiones benignas' },
  { code: 'L72.1', description: 'Quiste tricodérmico', category: 'Lesiones benignas' },

  { code: 'H02.3', description: 'Blefarocalasia', category: 'Facial y neuromuscular' },
  { code: 'H02.4', description: 'Blefaroptosis', category: 'Facial y neuromuscular' },
  { code: 'G24.5', description: 'Blefarospasmo', category: 'Facial y neuromuscular' },
  { code: 'G51.0', description: 'Parálisis de Bell', category: 'Facial y neuromuscular' },
  { code: 'F45.8', description: 'Otros trastornos somatomorfos', category: 'Facial y neuromuscular' },
  { code: 'M95.0', description: 'Deformidad adquirida de la nariz', category: 'Facial y neuromuscular' },
  { code: 'Q17.5', description: 'Oreja prominente', category: 'Facial y neuromuscular' },

  { code: 'T81.0', description: 'Hemorragia y hematoma que complican un procedimiento, no clasificados en otra parte', category: 'Complicaciones y eventos adversos' },
  { code: 'T81.4', description: 'Infección consecutiva a procedimiento, no clasificada en otra parte', category: 'Complicaciones y eventos adversos' },
  { code: 'T88.7', description: 'Efecto adverso no especificado de droga o medicamento', category: 'Complicaciones y eventos adversos' },
  { code: 'T78.4', description: 'Alergia no especificada', category: 'Complicaciones y eventos adversos' },
  { code: 'L92.3', description: 'Granuloma por cuerpo extraño en la piel y en el tejido subcutáneo', category: 'Complicaciones y eventos adversos' },
  { code: 'R60.0', description: 'Edema localizado', category: 'Complicaciones y eventos adversos' },
  { code: 'R22.0', description: 'Tumefacción, masa o prominencia localizada en la cabeza', category: 'Complicaciones y eventos adversos' },
  { code: 'L03.2', description: 'Celulitis de la cara', category: 'Complicaciones y eventos adversos' },
  { code: 'B00.1', description: 'Dermatitis vesicular herpética', category: 'Complicaciones y eventos adversos' },
  { code: 'L08.9', description: 'Infección local de la piel y del tejido subcutáneo, no especificada', category: 'Complicaciones y eventos adversos' },
  { code: 'L23.9', description: 'Dermatitis alérgica de contacto, de causa no especificada', category: 'Complicaciones y eventos adversos' },
  { code: 'L25.9', description: 'Dermatitis de contacto, forma y causa no especificadas', category: 'Complicaciones y eventos adversos' },
  { code: 'L27.0', description: 'Erupción cutánea generalizada debida a drogas y medicamentos', category: 'Complicaciones y eventos adversos' },
  { code: 'L30.9', description: 'Dermatitis, no especificada', category: 'Complicaciones y eventos adversos' },
  { code: 'L50.0', description: 'Urticaria alérgica', category: 'Complicaciones y eventos adversos' },
];
