/**
 * Catálogo CUPS odontología / ortodoncia (referencial, validar contra la resolución CUPS vigente).
 * Solo consultorio DENTISTRY; si el código no aparece se completa con la tabla general de CUPS.
 */
export const DENTISTRY_CUPS_CATALOG: Array<{ code: string; description: string }> = [
  // Consulta, diagnóstico y prevención
  { code: "890103", description: "Atención (visita) domiciliaria por odontología general" },
  { code: "890203", description: "Consulta de primera vez por odontología general" },
  { code: "890204", description: "Consulta de primera vez por odontología especializada" },
  { code: "890303", description: "Consulta de control o seguimiento por odontología general" },
  { code: "890304", description: "Consulta de control por odontología especializada" },
  { code: "890403", description: "Interconsulta por odontología general" },
  { code: "890404", description: "Interconsulta por odontología especializada" },
  { code: "890503", description: "Participación en junta médica u odontológica" },
  { code: "890703", description: "Consulta de urgencias por odontología general" },
  { code: "890704", description: "Consulta de urgencias por odontología especializada" },
  { code: "893101", description: "Impresión de arco dentario con modelo de estudio" },
  { code: "893102", description: "Fotografía clínica diagnóstica" },
  { code: "893103", description: "Evaluación y medición ortodóntica u ortopédica oral" },
  { code: "893104", description: "Estudio de oclusión y articulación temporomandibular" },
  { code: "893105", description: "Máscara facial diagnóstica ortodóncica" },
  { code: "893106", description: "Control de ortodoncia" },
  { code: "893107", description: "Elaboración y adaptación de aparato ortopédico" },
  { code: "893108", description: "Control de crecimiento y desarrollo dentomaxilofacial" },
  { code: "893109", description: "Examen de mucosa oral y periodontal" },
  { code: "893110", description: "Elaboración de aparato ortésico intraoral" },
  { code: "990203", description: "Educación individual en salud, por odontología" },
  { code: "990212", description: "Educación individual en salud, por higiene oral" },
  { code: "990103", description: "Educación grupal en salud, por odontología" },
  { code: "990112", description: "Educación grupal en salud, por higiene oral" },
  { code: "997001", description: "Profilaxis dental o pulido coronal" },
  { code: "997002", description: "Control de placa dental" },
  { code: "997103", description: "Topicación de flúor en gel" },
  { code: "997104", description: "Topicación de flúor en solución" },
  { code: "997105", description: "Aplicación de resina preventiva" },
  { code: "997106", description: "Topicación de flúor en barniz" },
  { code: "997107", description: "Aplicación de sellantes" },
  { code: "997301", description: "Detartraje supragingival" },
  // Odontología restauradora y rehabilitación
  { code: "232101", description: "Obturación dental con amalgama" },
  { code: "232102", description: "Obturación dental con resina de fotocurado" },
  { code: "232103", description: "Obturación dental con ionómero de vidrio" },
  { code: "232104", description: "Obturación dental, código genérico" },
  { code: "232201", description: "Obturación temporal por diente" },
  { code: "232301", description: "Colocación de pin intradentinario" },
  { code: "232401", description: "Reconstrucción de ángulo incisal" },
  { code: "232402", description: "Reconstrucción de tercio incisal" },
  { code: "232403", description: "Reconstrucción dental, código genérico" },
  { code: "233101", description: "Incrustación metálica" },
  { code: "233201", description: "Incrustación no metálica" },
  { code: "234101", description: "Corona en acero inoxidable para dentición temporal" },
  { code: "234102", description: "Corona en policarboxilato" },
  { code: "234103", description: "Corona en forma plástica" },
  { code: "234105", description: "Inserción o aplicación de corona, código genérico" },
  { code: "234106", description: "Corona provisional" },
  { code: "234201", description: "Prótesis fija, cada unidad" },
  { code: "234202", description: "Reconstrucción de muñones" },
  { code: "234204", description: "Reparación de prótesis fija" },
  { code: "234205", description: "Inserción de retenedor intrarradicular" },
  { code: "234301", description: "Prótesis removible parcial mucosoportada" },
  { code: "234302", description: "Prótesis removible parcial dentomucosoportada/implantosoportada" },
  { code: "234303", description: "Reparación de prótesis removible parcial" },
  { code: "234401", description: "Prótesis total mucosoportada, medio caso" },
  { code: "234402", description: "Prótesis total mucosoportada, caso completo" },
  { code: "234403", description: "Prótesis total implantoasistida, medio caso" },
  { code: "234404", description: "Prótesis total implantoasistida, caso completo" },
  { code: "235101", description: "Reimplante de diente" },
  { code: "235201", description: "Autotrasplante dental intencional" },
  { code: "236101", description: "Implante cerámico" },
  { code: "236201", description: "Implante metálico" },
  { code: "236301", description: "Implante dental oseointegrado" },
  // Endodoncia
  { code: "237102", description: "Pulpotomía" },
  { code: "237103", description: "Pulpectomía" },
  { code: "237201", description: "Apexificación" },
  { code: "237202", description: "Revascularización pulpar" },
  { code: "237203", description: "Recubrimiento pulpar directo" },
  { code: "237204", description: "Recubrimiento pulpar indirecto" },
  { code: "237301", description: "Terapia de conducto en diente unirradicular" },
  { code: "237302", description: "Terapia de conducto en diente birradicular" },
  { code: "237303", description: "Terapia de conducto en diente multirradicular" },
  { code: "237304", description: "Terapia de conducto en diente temporal unirradicular" },
  { code: "237305", description: "Terapia de conducto en diente temporal multirradicular" },
  { code: "237307", description: "Desobturación de conducto radicular" },
  { code: "237401", description: "Apicectomía" },
  { code: "237501", description: "Tratamiento correctivo de reabsorción radicular" },
  { code: "237502", description: "Tratamiento correctivo de fracturas radiculares" },
  { code: "237503", description: "Sellado quirúrgico de perforación endodóntica" },
  { code: "237504", description: "Sellado no quirúrgico de perforación endodóntica" },
  { code: "237505", description: "Remoción de retenedor intrarradicular" },
  { code: "237601", description: "Fistulización endodóntica por trepanación" },
  { code: "237602", description: "Fistulización endodóntica por incisión" },
  { code: "237603", description: "Fistulización endodóntica, código genérico" },
  { code: "237604", description: "Fistulización endodóntica por descompresión" },
  { code: "237701", description: "Radectomía por amputación única" },
  { code: "237702", description: "Radectomía por amputación múltiple" },
  { code: "237703", description: "Radectomía, código genérico" },
  { code: "237801", description: "Hemisección del diente" },
  { code: "237901", description: "Blanqueamiento dental intrínseco" },
  { code: "237903", description: "Blanqueamiento dental extrínseco" },
  // Periodoncia y cirugía oral
  { code: "230101", description: "Exodoncia de diente permanente unirradicular" },
  { code: "230102", description: "Exodoncia de diente permanente multirradicular" },
  { code: "230103", description: "Exodoncia de dientes permanentes, código genérico" },
  { code: "230201", description: "Exodoncia de diente temporal unirradicular" },
  { code: "230202", description: "Exodoncia de diente temporal multirradicular" },
  { code: "230203", description: "Exodoncia de dientes temporales, código genérico" },
  { code: "231101", description: "Exodoncia quirúrgica unirradicular" },
  { code: "231201", description: "Exodoncia quirúrgica multirradicular" },
  { code: "231301", description: "Exodoncia de diente incluido ectópico, abordaje intraoral" },
  { code: "231302", description: "Exodoncia de diente incluido ectópico, abordaje extraoral" },
  { code: "231303", description: "Exodoncia de diente incluido" },
  { code: "231401", description: "Exodoncias múltiples con alveoloplastia, por cuadrante" },
  { code: "240201", description: "Detartraje subgingival" },
  { code: "240301", description: "Alisado radicular, campo cerrado" },
  { code: "240401", description: "Drenaje de colección periodontal" },
  { code: "241101", description: "Biopsia incisional de encía" },
  { code: "241102", description: "Biopsia escisional de encía con cierre primario" },
  { code: "241103", description: "Biopsia escisional con colgajo o injerto" },
  { code: "241104", description: "Biopsia de encía, código genérico" },
  { code: "242201", description: "Curetaje a campo abierto" },
  { code: "242202", description: "Cirugía a colgajo con resección radicular" },
  { code: "242204", description: "Aumento de reborde edéntulo sin injerto" },
  { code: "242205", description: "Aumento de reborde edéntulo con injerto" },
  { code: "242301", description: "Plastias preprotésicas / aumento de corona clínica" },
  { code: "242401", description: "Reparación periodontal regenerativa" },
  { code: "243401", description: "Gingivectomía" },
  { code: "243502", description: "Operculectomía" },
  { code: "244101", description: "Enucleación de quiste odontogénico hasta 3 cm" },
  { code: "244102", description: "Enucleación de quiste odontogénico mayor de 3 cm" },
  { code: "244103", description: "Resección de tumor odontogénico" },
  { code: "244108", description: "Marsupialización de quiste" },
  { code: "245101", description: "Regularización de rebordes" },
  { code: "245201", description: "Alveolectomía" },
  // Ortodoncia y ortopedia dentofacial
  { code: "247001", description: "Colocación de anclaje temporal esquelético (TADs / mini-implantes)" },
  { code: "247101", description: "Colocación de aparatología fija para ortodoncia por arcada" },
  { code: "247201", description: "Colocación de aparatología removible intraoral" },
  { code: "247202", description: "Colocación de aparatología removible extraoral" },
  { code: "247301", description: "Colocación de aparatos de retención post-ortodoncia" },
  { code: "247401", description: "Ferulización rígida" },
  { code: "247402", description: "Ferulización semirrígida" },
  { code: "247403", description: "Ferulización, código genérico" },
  { code: "248101", description: "Cierre de diastema" },
  { code: "248201", description: "Tallado selectivo / ajuste oclusal" },
  { code: "248401", description: "Reparación de aparatología fija o removible" },
  { code: "248801", description: "Máscara facial terapéutica" },
  // Imágenes diagnósticas odontológicas
  { code: "870440", description: "Radiografía oclusal intraoral" },
  { code: "870450", description: "Radiografía periapical milimetrada" },
  { code: "870451", description: "Radiografía periapical de dientes anteriores superiores" },
  { code: "870452", description: "Radiografía periapical de dientes anteriores inferiores" },
  { code: "870453", description: "Radiografía periapical de zona de caninos" },
  { code: "870454", description: "Radiografía periapical de premolares" },
  { code: "870455", description: "Radiografía periapical de molares" },
  { code: "870456", description: "Juego completo de radiografías periapicales" },
  { code: "870460", description: "Radiografía coronal / aleta de mordida" },
];
