/** Catálogo CIE-10 odontología / ortodoncia (capítulo K00–K14 y afines). Solo consultorio DENTISTRY. */
export const DENTISTRY_CIE_CATALOG: Array<{ code: string; description: string; category?: string }> = [
  { code: "K000", description: "Anodoncia", category: "Desarrollo dentario" },
  { code: "K001", description: "Dientes supernumerarios", category: "Desarrollo dentario" },
  { code: "K002", description: "Anomalías del tamaño y de la forma del diente", category: "Desarrollo dentario" },
  { code: "K003", description: "Dientes moteados (fluorosis)", category: "Desarrollo dentario" },
  { code: "K004", description: "Alteraciones en la formación dentaria", category: "Desarrollo dentario" },
  { code: "K006", description: "Alteraciones en la erupción dentaria", category: "Desarrollo dentario" },
  { code: "K007", description: "Síndrome de la erupción dentaria", category: "Desarrollo dentario" },
  { code: "K010", description: "Dientes incluidos", category: "Dientes incluidos/impactados" },
  { code: "K011", description: "Dientes impactados", category: "Dientes incluidos/impactados" },
  { code: "K020", description: "Caries limitada al esmalte", category: "Caries" },
  { code: "K021", description: "Caries de la dentina", category: "Caries" },
  { code: "K022", description: "Caries del cemento", category: "Caries" },
  { code: "K023", description: "Caries dentaria detenida", category: "Caries" },
  { code: "K025", description: "Caries con exposición pulpar", category: "Caries" },
  { code: "K029", description: "Caries dental, no especificada", category: "Caries" },
  { code: "K030", description: "Atrición excesiva de los dientes", category: "Tejidos duros" },
  { code: "K031", description: "Abrasión de los dientes", category: "Tejidos duros" },
  { code: "K032", description: "Erosión de los dientes", category: "Tejidos duros" },
  { code: "K036", description: "Depósitos (acreciones) en los dientes", category: "Tejidos duros" },
  { code: "K038", description: "Otras enfermedades especificadas de los tejidos duros de los dientes", category: "Tejidos duros" },
  { code: "K040", description: "Pulpitis", category: "Pulpa y periápice" },
  { code: "K041", description: "Necrosis de la pulpa", category: "Pulpa y periápice" },
  { code: "K044", description: "Periodontitis apical aguda originada en la pulpa", category: "Pulpa y periápice" },
  { code: "K045", description: "Periodontitis apical crónica", category: "Pulpa y periápice" },
  { code: "K046", description: "Absceso periapical con fístula", category: "Pulpa y periápice" },
  { code: "K047", description: "Absceso periapical sin fístula", category: "Pulpa y periápice" },
  { code: "K048", description: "Quiste radicular", category: "Pulpa y periápice" },
  { code: "K050", description: "Gingivitis aguda", category: "Periodonto" },
  { code: "K051", description: "Gingivitis crónica", category: "Periodonto" },
  { code: "K052", description: "Periodontitis aguda", category: "Periodonto" },
  { code: "K053", description: "Periodontitis crónica", category: "Periodonto" },
  { code: "K054", description: "Periodontosis", category: "Periodonto" },
  { code: "K060", description: "Retracción gingival", category: "Periodonto" },
  { code: "K061", description: "Hiperplasia gingival", category: "Periodonto" },
  { code: "K070", description: "Anomalías evidentes del tamaño de los maxilares", category: "Anomalías dentofaciales / ortodoncia" },
  { code: "K071", description: "Anomalías de la relación maxilobasilar", category: "Anomalías dentofaciales / ortodoncia" },
  { code: "K072", description: "Anomalías de la relación entre los arcos dentarios", category: "Anomalías dentofaciales / ortodoncia" },
  { code: "K073", description: "Anomalías de la posición del diente", category: "Anomalías dentofaciales / ortodoncia" },
  { code: "K074", description: "Maloclusión de tipo no especificado", category: "Anomalías dentofaciales / ortodoncia" },
  { code: "K075", description: "Anomalías dentofaciales funcionales", category: "Anomalías dentofaciales / ortodoncia" },
  { code: "K076", description: "Trastornos de la articulación temporomaxilar", category: "Anomalías dentofaciales / ortodoncia" },
  { code: "K080", description: "Exfoliación de los dientes debida a causas sistémicas", category: "Otros dientes y soporte" },
  { code: "K081", description: "Pérdida de dientes debida a accidente, extracción o enfermedad periodontal local", category: "Otros dientes y soporte" },
  { code: "K082", description: "Atrofia del reborde alveolar desdentado", category: "Otros dientes y soporte" },
  { code: "K083", description: "Raíz dental retenida", category: "Otros dientes y soporte" },
  { code: "K088", description: "Otras afecciones especificadas de los dientes y de sus estructuras de sostén", category: "Otros dientes y soporte" },
  { code: "K090", description: "Quistes originados por el desarrollo de los dientes", category: "Quistes" },
  { code: "K102", description: "Afecciones inflamatorias de los maxilares", category: "Maxilares" },
  { code: "K103", description: "Alveolitis del maxilar", category: "Maxilares" },
  { code: "K115", description: "Sialolitiasis", category: "Glándulas salivales" },
  { code: "K117", description: "Alteraciones de la secreción salival", category: "Glándulas salivales" },
  { code: "K120", description: "Estomatitis aftosa recurrente", category: "Mucosa oral" },
  { code: "K121", description: "Otras formas de estomatitis", category: "Mucosa oral" },
  { code: "K122", description: "Celulitis y absceso de boca", category: "Mucosa oral" },
  { code: "K130", description: "Enfermedades de los labios", category: "Mucosa oral" },
  { code: "K132", description: "Leucoplasia y otras alteraciones del epitelio bucal", category: "Mucosa oral" },
  { code: "K137", description: "Otras lesiones y las no especificadas de la mucosa bucal", category: "Mucosa oral" },
  { code: "K140", description: "Glositis", category: "Lengua" },
  { code: "K141", description: "Lengua geográfica", category: "Lengua" },
  { code: "S025", description: "Fractura de los dientes", category: "Trauma" },
  { code: "S032", description: "Luxación de diente", category: "Trauma" },
  { code: "Z012", description: "Examen odontológico", category: "Control" },
  { code: "Z463", description: "Prueba y ajuste de prótesis dental", category: "Control" },
  { code: "Z464", description: "Prueba y ajuste de dispositivo ortodóncico", category: "Control" },
];
