/** Catálogo CUPS psicología / psiquiatría (Res. 2292 / procedimientos ambulatorios). */
export const PSYCHOLOGY_CUPS_CATALOG: Array<{ code: string; description: string }> = [
  { code: '890108', description: 'Atención (visita) domiciliaria por psicología' },
  { code: '890208', description: 'Consulta de primera vez por psicología' },
  { code: '890284', description: 'Consulta de primera vez por especialista en psiquiatría' },
  { code: '890285', description: 'Consulta de primera vez por especialista en psiquiatría pediátrica' },
  { code: '890297', description: 'Consulta de primera vez por otras especialidades de psicología' },
  { code: '890308', description: 'Consulta de control o seguimiento por psicología' },
  { code: '890384', description: 'Consulta de control o seguimiento por especialista en psiquiatría' },
  { code: '890385', description: 'Consulta de control o seguimiento por especialista en psiquiatría pediátrica' },
  { code: '890397', description: 'Consulta de control o seguimiento por otras especialidades de psicología' },
  { code: '890408', description: 'Interconsulta por psicología' },
  { code: '890484', description: 'Interconsulta por especialista en psiquiatría' },
  { code: '890485', description: 'Interconsulta por especialista en psiquiatría pediátrica' },
  { code: '890608', description: 'Asistencia intrahospitalaria por psicología' },
  { code: '940101', description: 'Administración/aplicación de prueba de inteligencia' },
  { code: '940201', description: 'Administración/aplicación de prueba de personalidad' },
  { code: '940301', description: 'Evaluación en alteraciones emocionales (afectivas) o de conducta' },
  { code: '940302', description: 'Aplicación de prueba en alteraciones emocionales o de conducta' },
  { code: '940701', description: 'Administración/aplicación de prueba neuropsicológica' },
  { code: '940901', description: 'Determinación del estado mental por psicología' },
  { code: '941101', description: 'Determinación del estado mental por psiquiatría' },
  { code: '941400', description: 'Evaluación de salud mental por equipo interdisciplinario' },
  { code: '943101', description: 'Psicoterapia individual por psiquiatría' },
  { code: '943102', description: 'Psicoterapia individual por psicología' },
  { code: '943500', description: 'Intervención en crisis SOD' },
  { code: '944001', description: 'Psicoterapia de pareja por psiquiatría' },
  { code: '944002', description: 'Psicoterapia de pareja por psicología' },
  { code: '944101', description: 'Psicoterapia familiar por psiquiatría' },
  { code: '944102', description: 'Psicoterapia familiar por psicología' },
  { code: '944201', description: 'Psicoterapia de grupo por psiquiatría' },
  { code: '944202', description: 'Psicoterapia de grupo por psicología' },
  { code: '944902', description: 'Intervención en salud mental comunitaria por psiquiatría' },
  { code: '944904', description: 'Intervención en salud mental comunitaria por psicología' },
  { code: '944905', description: 'Intervención en salud mental comunitaria por trabajo social' },
  { code: '944910', description: 'Intervención en salud mental comunitaria por otro profesional de salud' },
  { code: '944915', description: 'Intervención en salud mental comunitaria por equipo interdisciplinario' },
];
